### ISSUE TITLE
Error using the dns_nsupdate 

### ISSUE THREAD

**Issue by kfoon** [pini-gh/acme-companion#27]
I set the the dns mode to dns_nsupdate but and get all the env variable but when the container is started it got error:

`[Wed Oct 13 13:31:00 UTC 2021] Adding txt value: Eh9iEDbc--mL80p5IaSt32LVLKUcqusjB73E8hOclbg for domain:  _acme-challenge.xxxxxx.com
[Wed Oct 13 13:31:01 UTC 2021] adding _acme-challenge.xxxxx.com. 60 in txt "Eh9iEDbc--mL80p5IaSt32LVLKUcqusjB73E8hOclbg"
/app/dnsapi/dns_nsupdate.sh: line 35: nsupdate: command not found
[Wed Oct 13 13:31:01 UTC 2021] error updating domain
[Wed Oct 13 13:31:01 UTC 2021] Error add txt for domain:_acme-challenge.xxxxxx.com
[Wed Oct 13 13:31:01 UTC 2021] Please check log file for more details: /dev/null`

it looks like the container has to be build also with the nsupdate package, can you help with this

**Comment by pini-gh** [comment]
Sure. Would you mind giving a try at running `apk add bind-tools` in your instance, and see if that does the trick? If so i'll update the image accordingly.
