### ISSUE TITLE
nginx default configured IP different from actual container IP

### ISSUE THREAD

**Issue by kfoon** [pini-gh/acme-companion#30]
I restarted my docker host and how when i type the a domain am getting the wrong container, doing docker inspect on the container and comparing the nginx default configuration i see that its not ping to the same IP, is it possible to make the nginx.tmpl use the container name instead of the IP

**Comment by pini-gh** [comment]
I don't understand your request. Could you give more details?

**Comment by kfoon** [comment]
This can now be close, the issue was the nginx gen was not running so the default nginx did not update with the new container IP and was serving the wrong containers.
